# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 16:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('date_end', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('export_turnover', models.FloatField(blank=True, default=0, help_text='\u041e\u0431\u043e\u0440\u043e\u0442 \u043f\u043e \u043a\u0440\u0435\u0434\u0438\u0442\u0443', verbose_name='\u042d\u043a\u0441\u043f\u043e\u0440\u0442')),
                ('import_turnover', models.FloatField(blank=True, default=0, help_text='\u041e\u0431\u043e\u0440\u043e\u0442 \u043f\u043e \u0434\u0435\u0431\u0438\u0442\u0443', verbose_name='\u0418\u043c\u043f\u043e\u0440\u0442')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('name', models.CharField(help_text='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438', max_length=80, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='\u041a\u043e\u0434 iso')),
                ('name', models.CharField(help_text='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u044b', max_length=80, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Negotiator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
            options={
                'verbose_name_plural': 'Negotiator',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430')),
                ('date_end', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Active'), (3, 'Reconciliation'), (4, 'Closed')], help_text='\u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u043f\u0435\u0440\u0438\u043e\u0434\u0430', verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441')),
                ('is_last', models.BooleanField(default=False)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.Agreement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.Country'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.Company'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='negotiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.Negotiator'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('name', 'country')]),
        ),
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together=set([('company', 'date_start', 'date_end')]),
        ),
    ]
